# simple main.yml file
name: React CI

on:
    push:  #task 4
        branches: [main, master, features/tests]

jobs:
    build:
        runs-on: ubuntu-latest # linux distribution
        # sets up ubuntu environment to run following code off of
        steps:
          - name: Check out code
            uses: actions/checkout@v2 # checks out repo and provides it access
            #within ubuntu environment to following steps
          - name: use Node.js
            uses: actions/setup-node@v2 
            with: 
                node-version: '20'

          - name: Install dependencies
            run: npm ci # github actions runs better off npm ci instead of npm i
       
          - name: Print debugging information
            run: | 
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                echo "Working Dictionary: $(pwd)"
                echo "Contents of Working Directory: $(ls -l)"
                echo "Contents of node_modules: $(ls -l node_modules)"
    test:
      runs-on: ubuntu-latest

      steps: 
          - name: check out code
            uses: actions/checkout@v2

          - name: use Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '20'
          
          - name: Install dependencies
            run: npm  ci

          - name: Run Tests
            run: npm test
